services:
  app:
    image: reholly/article-service:v1.0.2
    depends_on:
      - db
    networks:
      - default
  db:
    restart: always
    image: postgres
    volumes:
      - ./.database/postgres/data:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB}
    networks:
      - default
    ports:
      - "5435:5432"